# Generated by Django 5.1.4 on 2025-05-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('chat', 'Chat'), ('chien', 'Chien'), ('lapin', 'Lapin')], max_length=10)),
                ('race', models.CharField(max_length=100)),
                ('naissance', models.DateField()),
                ('poids', models.FloatField()),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='owners.owner')),
            ],
        ),
    ]
