# Generated by Django 5.1.4 on 2025-06-04 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(choices=[('CAT', 'Chat'), ('DOG', 'Chien'), ('RABBIT', 'Lapin')], max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('weight', models.FloatField()),
                ('sex', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner')),
            ],
        ),
    ]
